// [FIREBASE REALTIME DB SCHEMA]
// Path: games/taut/{roomId}
//
// Firebase is the single source of truth. LocalVarsMap/ModuleAnswerMap are keyed by
// module id so every module state and every submitted answer is strictly typed
// (no `any` anywhere in the app).

export type Difficulty = "BEGINNER" | "STANDARD" | "EXTREME";
export type RoomStatus = "LOBBY" | "PLAYING" | "LEVEL_CLEARED" | "GAME_OVER" | "VICTORY";
export type Direction = "UP" | "RIGHT" | "DOWN" | "LEFT";

/* ------------------------------------------------------------------ *
 * Module vocabularies (exactly as named in .ai_docs/modules)
 * ------------------------------------------------------------------ */
export type MazeId = "Alpha" | "Beta" | "Gamma";
/** What the holder physically did with the big button. */
export type ButtonAction = "EARLY" | "HOLD_TO_TARGET" | "RELEASE_NOW";
/**
 * MOD_03 vocabularies for the cascading button ruleset. White is deliberately excluded from
 * both the button and the light: a white lit LED is hard to distinguish from the unlit/OFF
 * state, so Green is used instead.
 */
export type ButtonColor = "Red" | "Blue" | "Green" | "Yellow";
export type ButtonLabel = "Abort" | "Detonate" | "Hold" | "Press";
/** Colour of the indicator light (ignored when `lightState` is "OFF"). */
export type LightColor = "Red" | "Blue" | "Green" | "Yellow";
/** Indicator light state: dark, steady, or blinking. */
export type LightState = "OFF" | "SOLID" | "FLASHING";
/** The two actions the cascading ruleset can resolve to. */
export type ButtonDirective = "HOLD" | "DROP";
export type HazardSymbol = "Biohazard" | "Radiation" | "Corrosive";
export type ShapeId = "Triangle" | "Square" | "Hexagon" | "Circle";
export type WarningLight = "FLASHING" | "SOLID";
export type HardwareRevision = "Rev 1.0" | "Rev 1.2" | "Rev 1.4";
export type Constellation =
  | "Ursa"
  | "Orion"
  | "Draco"
  | "Lyra"
  | "Cassiopeia"
  | "Cygnus"
  | "Aquila"
  | "Pegasus"
  | "Corvus"
  | "Vela";
/** The 8 real-world compass directions (no compound 3-letter directions). */
export type WindDirection =
  | "North"
  | "NorthEast"
  | "East"
  | "SouthEast"
  | "South"
  | "SouthWest"
  | "West"
  | "NorthWest";
export type SynthTarget =
  | "Type A"
  | "Type B"
  | "Type C"
  | "Type D"
  | "Type E"
  | "Type F"
  | "Type G"
  | "Type H"
  | "Type I"
  | "Type J";
export type VialId =
  | "Alpha"
  | "Beta"
  | "Gamma"
  | "Delta"
  | "Epsilon"
  | "Zeta"
  | "Eta"
  | "Theta"
  | "Iota"
  | "Kappa";
export type ValveId = "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H";
export type IntercomMessage =
  | "KOSONG"
  | "APA"
  | "TUNGGU"
  | "BENTAR"
  | "HAH"
  | "SPASI"
  | "TITIK"
  | "GAK ADA"
  | "UDAH"
  | "BELUM";
export type IntercomResponse =
  | "ISI"
  | "ULANG"
  | "LANJUT"
  | "TEKAN"
  | "BIARIN"
  | "HAPUS"
  | "KOMA"
  | "TITIK"
  | "TIDAK"
  | "IYA"
  | "ITU";
export type Threat = "Laser" | "Plasma" | "Kinetic" | "Sonic" | "EMP" | "Acid" | "Railgun";
export type RoomHazard = "Kitchen" | "Armory" | "Server" | "Laboratory" | "Reactor" | "Hangar" | "Vault";
export type FilterState = "Active" | "Standby";
export type SorterColor = "Red" | "Green" | "Blue" | "Yellow";
export type SorterShape = "Triangle" | "Square" | "Circle";
export type SorterObject = { readonly color: SorterColor; readonly shape: SorterShape };
export type DocumentCode =
  | "Doc-12"
  | "Doc-45"
  | "Doc-77"
  | "Doc-03"
  | "Doc-28"
  | "Doc-51"
  | "Doc-64"
  | "Doc-89"
  | "Doc-90"
  | "Doc-33";
export type TubeColor = "Red" | "Blue" | "Green" | "Yellow";
export type PersonName =
  | "Rizki Pratama"
  | "Rizky Pratama"
  | "Chairul Anwar"
  | "Khairul Anwar"
  | "Syifa Aulia"
  | "Sifa Aulia"
  | "Fikri Saputra"
  | "Vikri Saputra"
  | "Naufal Hakim"
  | "Noval Hakim";
export type Destination =
  | "Break Room"
  | "Brake Room"
  | "Wait Room"
  | "Weight Room"
  | "Sensor Lab"
  | "Censor Lab"
  | "Council Hall"
  | "Counsel Hall"
  | "Site A"
  | "Sight A";

/** Five unlabeled power switches. */
export type Switches = readonly [boolean, boolean, boolean, boolean, boolean];
/** Equalizer band ids; a difficulty may use a prefix of these (3 / 5 / 7 bands). */
export type BandId = "bass" | "lowMid" | "mid" | "highMid" | "treble" | "presence" | "air";
/** Physical slider positions keyed by band id. */
export type Sliders = Partial<Record<BandId, number>>;

/* ------------------------------------------------------------------ *
 * Host-generated state per module ("Generated by host on start")
 * ------------------------------------------------------------------ */
export interface LocalVarsMap {
  MOD_01_WIRE: {
    serialNumber: string;
    wireCount: 3 | 4 | 5 | 6;
    /** Actual color of each wire, top to bottom, from {Red, White, Blue, Yellow, Black}. */
    wireColors: string[];
    /** Left pin (1..6) for each wire, strictly increasing so no wires cross. */
    leftPins: number[];
    /** Right pin (1..6) for each wire, strictly increasing so no wires cross. */
    rightPins: number[];
    cutIndex: number | null;
  };
  MOD_02_INVISIBLE_MAZE: {
    mazeId: MazeId;
    startCoord: string;
    finishCoord: string;
    currentCoord: string;
    serialNumber: string;
  };
  MOD_03_BUTTON: {
    buttonColor: ButtonColor;
    buttonLabel: ButtonLabel;
    lightColor: LightColor;
    lightState: LightState;
    serialNumber: string;
    isHolding: boolean;
    holdStartedAt: number | null;
  };
  MOD_04_SEQUENCE_PROTOCOL: {
    /** Labels of the 4 physical buttons, left to right (reshuffled every stage). */
    physicalLabels: number[];
    /** Digit shown on the display for each of the 4 stages. */
    stageDisplays: number[];
    currentStage: number;
    history: { positionPressed: number; labelPressed: number }[];
    /** Advances each stage; used to reshuffle the labels deterministically. */
    labelSeed: number;
  };
  MOD_05_CHEMISTRY: {
    hazardSymbol: HazardSymbol;
  };
  MOD_06_POWER_GRID: {
    serialNumber: string;
    warningLight: WarningLight;
    switches: Switches;
  };
  MOD_07_EQUALIZER: {
    serialNumber: string;
    hardwareRevision: HardwareRevision;
    /** Active bands for this instance (difficulty-scaled: 3 / 5 / 7). */
    bands: BandId[];
  };
  MOD_08_RADAR: {
    constellation: Constellation;
    windDirection: WindDirection;
    /** Independently rolled drift magnitude (1–2) for each wind direction this instance. */
    driftMagnitudes: Record<WindDirection, number>;
    /** Per-instance constellations to show in Info 1 (correct answer among them). */
    constellations: Constellation[];
    /** Per-instance wind directions to show in Info 2 (correct answer among them). */
    windDirections: WindDirection[];
  };
  MOD_09_SYNTHESIZER: {
    targetType: SynthTarget;
    /** Per-instance target types to show in Info 1. */
    targetTypes: SynthTarget[];
    /** Per-instance vials to show in Info 2 (the matching one is among them). */
    vialIds: VialId[];
  };
  MOD_10_PRESSURE_VALVES: {
    serialNumber: string;
    currentPressure: number;
    /** Per-instance valves on the panel (difficulty-scaled: 4 / 6 / 8). */
    activeValves: ValveId[];
    /** The owner's currently-open valves. */
    valves: ValveId[];
  };
  MOD_11_INTERCOM: {
    incomingMessage: IntercomMessage;
    /** Per-instance incoming words to show in Info 1 (the owner's word is among them). */
    messages: IntercomMessage[];
    /** Per-instance reply options to show in Info 2. */
    responses: IntercomResponse[];
  };
  MOD_12_SAFE_ZONE: {
    threat: Threat;
    room: RoomHazard;
    /** Grid is gridSize x gridSize (columns A.., rows 1..gridSize). */
    gridSize: number;
    /** Per-instance cells each listed threat covers. */
    threatCells: Record<string, string[]>;
    /** Per-instance cells each listed room covers. */
    roomCells: Record<string, string[]>;
  };
  MOD_13_SHAPE_SORTER: {
    filterAlpha: FilterState;
    filterBeta: FilterState;
    objects: SorterObject[];
  };
  MOD_14_PNEUMATIC_TUBE: {
    documentCode: DocumentCode;
    /** Per-instance documents to show in Info 1 (the owner's document is among them). */
    documents: DocumentCode[];
  };
  MOD_15_BIOMETRIC_SCANNER: {
    personName: PersonName;
    destination: Destination;
    /** Per-instance people to show in Info 2 (the scanned person is among them). */
    people: PersonName[];
    /** Per-instance destinations to show in Info 1 (the target is among them). */
    destinations: Destination[];
  };
}

export type ModuleId = keyof LocalVarsMap;

/** What the holder submits for each module. */
export interface ModuleAnswerMap {
  MOD_01_WIRE: { wireIndex: number };
  MOD_02_INVISIBLE_MAZE: { direction: Direction };
  MOD_03_BUTTON: { action: ButtonAction; secondsLeft: number };
  MOD_04_SEQUENCE_PROTOCOL: { position: number };
  MOD_05_CHEMISTRY: { buttonsPressed: ShapeId[] };
  MOD_06_POWER_GRID: { switches: Switches };
  MOD_07_EQUALIZER: Sliders;
  MOD_08_RADAR: { coord: string };
  MOD_09_SYNTHESIZER: { vial: VialId };
  MOD_10_PRESSURE_VALVES: { valves: ValveId[] };
  MOD_11_INTERCOM: { response: IntercomResponse };
  MOD_12_SAFE_ZONE: { coord: string };
  MOD_13_SHAPE_SORTER: { objectIndex: number };
  MOD_14_PNEUMATIC_TUBE: { tube: TubeColor };
  MOD_15_BIOMETRIC_SCANNER: { action: "APPROVE" | "REJECT" };
}

export interface ModuleState<K extends ModuleId = ModuleId> {
  moduleId: K;
  isSolved: boolean;
  localVars: LocalVarsMap[K];
}

export type AnyModuleState = { [K in ModuleId]: ModuleState<K> }[ModuleId];

export interface PlayerState {
  id: string;
  name: string;
  joinedAt: number;
  isReady: boolean;
  informant1Id: string; // Target player ID holding Info 1
  informant2Id: string; // Target player ID holding Info 2
  activeModules: Record<string, AnyModuleState>;
}

export interface LastStrike {
  playerId: string;
  moduleName: string;
  at: number;
}

export interface RoomState {
  id: string;
  hostId: string;
  status: RoomStatus;
  difficulty: Difficulty;
  /** 1-based current level; difficulty may run several levels of "one module per player". */
  level: number;
  /** Total levels for this difficulty (1 for Beginner). */
  totalLevels: number;
  globalEndTime: number; // Unix timestamp for local client countdown calculation
  strikeCount: number;
  maxStrikes: number;
  lastStrike: LastStrike | null;
  owners: Record<string, true>;
  players: Record<string, PlayerState>;
}
