// [FIREBASE REALTIME DB SCHEMA]
// Path: games/taut/{roomId}
//
// Firebase is the single source of truth. LocalVarsMap/ModuleAnswerMap are keyed by
// module id so every module state and every submitted answer is strictly typed
// (no `any` anywhere in the app).

export type Difficulty = "BEGINNER" | "STANDARD" | "EXTREME";
export type RoomStatus = "LOBBY" | "PLAYING" | "LEVEL_CLEARED" | "GAME_OVER" | "VICTORY";
export type Direction = "UP" | "RIGHT" | "DOWN" | "LEFT";

/* ------------------------------------------------------------------ *
 * Module vocabularies (exactly as named in .ai_docs/modules)
 * ------------------------------------------------------------------ */
export type MazeId = "Alpha" | "Beta" | "Gamma";
export type Cipher = "XYZA" | "VBNM";
/** What the holder physically did with the big button. */
export type ButtonAction = "EARLY" | "HOLD_TO_TARGET" | "RELEASE_NOW";
export type HazardSymbol = "Biohazard" | "Radiation" | "Corrosive";
export type ShapeId = "Triangle" | "Square" | "Hexagon" | "Circle";
export type WarningLight = "FLASHING" | "SOLID";
export type HardwareRevision = "Rev 1.0" | "Rev 1.2" | "Rev 1.4";
export type Constellation = "Ursa" | "Orion" | "Draco";
export type WindDirection = "North" | "East" | "South";
export type SynthTarget = "Type A" | "Type B" | "Type C";
export type VialId = "Alpha" | "Beta" | "Gamma" | "Delta";
export type ValveId = "A" | "B" | "C" | "D";
export type IntercomMessage = "KLAATU" | "GORT" | "VERATA";
export type IntercomResponse = "BARADA" | "NIKTO" | "SHREK" | "FIONA";
export type Threat = "Laser" | "Plasma" | "Kinetic";
export type RoomHazard = "Kitchen" | "Armory" | "Server";
export type FilterState = "Active" | "Standby";
export type SorterColor = "Red" | "Green" | "Blue" | "Yellow";
export type SorterShape = "Triangle" | "Square" | "Circle";
export type SorterObject = { readonly color: SorterColor; readonly shape: SorterShape };
export type DocumentCode = "Doc-12" | "Doc-45" | "Doc-77";
export type TubeColor = "Red" | "Blue" | "Green" | "Yellow";
export type PersonName = "Jane Smith" | "John Doe" | "Alan Turing";
export type Destination = "Maintenance" | "Engineering" | "Server Room";

/** Five unlabeled power switches. */
export type Switches = readonly [boolean, boolean, boolean, boolean, boolean];
export type Sliders = { readonly bass: number; readonly mid: number; readonly treble: number };

/* ------------------------------------------------------------------ *
 * Host-generated state per module ("Generated by host on start")
 * ------------------------------------------------------------------ */
export interface LocalVarsMap {
  MOD_01_WIRE: {
    serialNumber: string;
    wireCount: 3 | 4;
    cutIndex: number | null;
  };
  MOD_02_INVISIBLE_MAZE: {
    mazeId: MazeId;
    startCoord: string;
    finishCoord: string;
    currentCoord: string;
  };
  MOD_03_BUTTON: {
    cipher: Cipher;
    serialNumber: string;
    isHolding: boolean;
    holdStartedAt: number | null;
  };
  MOD_04_SEQUENCE_PROTOCOL: {
    /** Labels of the 4 physical buttons, left to right (randomised 1-4). */
    physicalLabels: number[];
    /** Digit shown on the display for each of the 4 stages. */
    stageDisplays: number[];
    currentStage: number;
    history: { positionPressed: number; labelPressed: number }[];
  };
  MOD_05_CHEMISTRY: {
    hazardSymbol: HazardSymbol;
  };
  MOD_06_POWER_GRID: {
    serialNumber: string;
    warningLight: WarningLight;
    switches: Switches;
  };
  MOD_07_EQUALIZER: {
    serialNumber: string;
    hardwareRevision: HardwareRevision;
  };
  MOD_08_RADAR: {
    constellation: Constellation;
    windDirection: WindDirection;
  };
  MOD_09_SYNTHESIZER: {
    targetType: SynthTarget;
  };
  MOD_10_PRESSURE_VALVES: {
    serialNumber: string;
    currentPressure: number;
    valves: ValveId[];
  };
  MOD_11_INTERCOM: {
    incomingMessage: IntercomMessage;
  };
  MOD_12_SAFE_ZONE: {
    threat: Threat;
    room: RoomHazard;
  };
  MOD_13_SHAPE_SORTER: {
    filterAlpha: FilterState;
    filterBeta: FilterState;
    objects: SorterObject[];
  };
  MOD_14_PNEUMATIC_TUBE: {
    documentCode: DocumentCode;
  };
  MOD_15_BIOMETRIC_SCANNER: {
    personName: PersonName;
    destination: Destination;
  };
}

export type ModuleId = keyof LocalVarsMap;

/** What the holder submits for each module. */
export interface ModuleAnswerMap {
  MOD_01_WIRE: { wireIndex: number };
  MOD_02_INVISIBLE_MAZE: { direction: Direction };
  MOD_03_BUTTON: { action: ButtonAction; secondsLeft: number };
  MOD_04_SEQUENCE_PROTOCOL: { position: number };
  MOD_05_CHEMISTRY: { buttonsPressed: ShapeId[] };
  MOD_06_POWER_GRID: { switches: Switches };
  MOD_07_EQUALIZER: Sliders;
  MOD_08_RADAR: { coord: string };
  MOD_09_SYNTHESIZER: { vial: VialId };
  MOD_10_PRESSURE_VALVES: { valves: ValveId[] };
  MOD_11_INTERCOM: { response: IntercomResponse };
  MOD_12_SAFE_ZONE: { coord: string };
  MOD_13_SHAPE_SORTER: { objectIndex: number };
  MOD_14_PNEUMATIC_TUBE: { tube: TubeColor };
  MOD_15_BIOMETRIC_SCANNER: { action: "APPROVE" | "REJECT" };
}

export interface ModuleState<K extends ModuleId = ModuleId> {
  moduleId: K;
  isSolved: boolean;
  localVars: LocalVarsMap[K];
}

export type AnyModuleState = { [K in ModuleId]: ModuleState<K> }[ModuleId];

export interface PlayerState {
  id: string;
  name: string;
  joinedAt: number;
  isReady: boolean;
  informant1Id: string; // Target player ID holding Info 1
  informant2Id: string; // Target player ID holding Info 2
  activeModules: Record<string, AnyModuleState>;
}

export interface LastStrike {
  playerId: string;
  moduleName: string;
  at: number;
}

export interface RoomState {
  id: string;
  hostId: string;
  status: RoomStatus;
  difficulty: Difficulty;
  /** 1-based current level; difficulty may run several levels of "one module per player". */
  level: number;
  /** Total levels for this difficulty (1 for Beginner). */
  totalLevels: number;
  globalEndTime: number; // Unix timestamp for local client countdown calculation
  strikeCount: number;
  maxStrikes: number;
  lastStrike: LastStrike | null;
  owners: Record<string, true>;
  players: Record<string, PlayerState>;
}
