// [FIREBASE REALTIME DB SCHEMA]

export interface RoomState {
  id: string;
  hostId: string;
  status: "LOBBY" | "PLAYING" | "GAME_OVER" | "VICTORY";
  difficulty: "BEGINNER" | "STANDARD" | "EXTREME";
  globalEndTime: number; // Unix timestamp for local client countdown calculation
  strikeCount: number;
  maxStrikes: number;
  players: Record<string, PlayerState>;
}

export interface PlayerState {
  id: string;
  name: string;
  informant1Id: string; // Target player ID holding Info 1
  informant2Id: string; // Target player ID holding Info 2
  activeModules: Record<string, ModuleState>;
}

export interface ModuleState {
  moduleId: string; // e.g., "MOD_01_WIRE", "MOD_06_POWER_GRID"
  isSolved: boolean;
  localVars: Record<string, any>; // Generated by host on start
}